- name: Add key for deadsnakes PPA
  apt_key:
       keyserver: keyserver.ubuntu.com
       id: F23C5A6CF475977595C89F51BA6932366A755776
       state: present

- name: Add deadsnakes PPA
  apt_repository:
       repo: deb http://ppa.launchpad.net/deadsnakes/nightly/ubuntu bionic main
       state: present

- name: Install Python 3.8
  apt:
       name: python3.8
       state: present
       update_cache: yes

- name: Install pip3
  apt:
       name: python3-pip
       state: present
       update_cache: yes

- name: Install 'virtualenv' package
  pip:
       name: virtualenv
       executable: pip3

- name: create env for flask
  shell: "python3 -m venv venv; . venv/bin/activate"

- name: install flask with pip
  pip:
       name: flask
       executable: pip3

- name: install Werkzeug with pip
  pip:
       name: Werkzeug
       executable: pip3

- name: Create virtualenv
  become: no
  pip:
       virtualenv: "{{ venv_path }}"
       virtualenv_python: python3.8
       requirements: "{{ requirements_path }}"

- name: create dir for repo as sudo
  file:
       path: /webapps/devops
       state: directory
       owner: vagrant
       group: vagrant


- name: clone repo
  become: no
  git:
       repo: 'https://github.com/sigidpam/devops-challenge-la.git'
       dest: /webapps/devops

- name: check and install dependencies modules
  shell: "pip3 install --upgrade setuptools; pip3 install flask commentjson requests werkzeug==0.16.0"
  
- name: Launch Flask website  
  shell: "cd /webapps/devops; sudo nohup flask run --host 10.10.10.20  2>&1 >/dev/null &" 
